---
# file: pip.yml
#

  #removing pip installation part as its already installed in Vagrnatfile.
  # - name: Install pip
  #   yum:
   #    name: python-pip
   #    state: present
   - name: Installing requirements
     pip:
       requirements: "{{ installation_dir }}/requirements.txt"
   - name: Change Timzone of machine to UTC
     timezone:
       name: UTC

  
